### ISSUE TITLE
Can't get a response to API calls (course)

### ISSUE THREAD

**Issue by MaorRayzin** [igalshapira/ziggi3#2]
after trying to post this: 
{'number': '101.1.0117', year: 1, semester: 1}

I get this a bad request error and this is the error showed in the npm console:

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.header (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/response.js:249:15)
    at ServerResponse.send (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/response.js:151:21)
    at /Users/maorreyzin/Dev/ziggi/ziggi3/app/api/courses.js:83:39
    at Layer.handle [as handle_request] (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/layer.js:95:5)
    at /Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:312:13)
    at /Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:271:10)
    at /Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express-validator/lib/express_validator.js:291:5
    at Layer.handle [as handle_request] (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/maorreyzin/Dev/ziggi/ziggi3/node_modules/express/lib/router/index.js:312:13)

**Comment by igalshapira** [comment]
It is surely a bug. The right error you suppose to get is 'invalid year'

But your input is not correct anyway - please see: index.js:isYear

```
 return val >= 2015;
```

**Comment by igalshapira** [comment]
Resolved in 745eaa4dcee8be421517a5855ea90d2c6bc4dc35
